# docker-compose up -d
# docker-compose down
# docker exec -it freepbx bash

version: '2'
services:
  freepbx:
    build: .
    image: mima84/docker-freepbx
    container_name: freepbx
    network_mode: "host"
    volumes:
    - ~/.freepbx/backup:/var/spool/asterisk/backup
